# Generated by Django 2.1.8 on 2019-05-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(blank=True, help_text='Name of Club', max_length=100, primary_key=True, serialize=False, verbose_name='Club Name')),
                ('club_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of the Event', max_length=100, verbose_name='Event Name')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Event Date')),
                ('start_time', models.TimeField(help_text='Starting time of event', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Finishing time of event', verbose_name='Finish Time')),
                ('club_image', models.ImageField(null=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Club')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
