# Generated by Django 2.2.1 on 2019-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.CharField(blank=True, help_text='Club hosting event', max_length=100, null=True, verbose_name='Club Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the Event', max_length=100, null=True, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Day of the event', verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Finishing time of event', verbose_name='Finish Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Starting time of event', verbose_name='Start Time'),
        ),
    ]
