# Generated by Django 2.2.1 on 2019-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190515_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club_image',
            field=models.ImageField(blank=True, height_field=20, null=True, upload_to='uploads/', width_field=20),
        ),
    ]
