# Generated by Django 2.1.8 on 2019-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190523_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Location', max_length=100, verbose_name='Location'),
        ),
    ]
