# Generated by Django 2.1.8 on 2019-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price', max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
