# Generated by Django 2.2.1 on 2019-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
