# Generated by Django 2.2.1 on 2019-05-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190515_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
