# Generated by Django 2.1.8 on 2019-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190523_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fb',
            field=models.CharField(blank=True, help_text='Event Link', max_length=100, verbose_name='Facebook Event'),
        ),
    ]
