# Generated by Django 2.1.8 on 2019-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='club',
            name='fb',
            field=models.CharField(blank=True, help_text='Event Link', max_length=100, verbose_name='Facebook Event'),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, help_text='Location', max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.CharField(blank=True, help_text='Location', max_length=100, verbose_name='Location'),
        ),
    ]
