# Generated by Django 2.1.8 on 2019-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190530_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='followed',
            field=models.BooleanField(help_text='Followed', null=True, verbose_name='Followed'),
        ),
    ]
